### ISSUE TITLE
Column of blank values in transit matrix output

### ISSUE THREAD

**Issue by gyoliver** [GeoDaCenter/spatial_access#26]
An extra column of blank string values (rightmost column) is getting written into the transit matrix.  TransitMatrix.write_to_file() fails when it tries to cast the blank values as floats.  

Below is the error that gets thrown:

Traceback (most recent call last):

  File "command_line_test.py", line 87, in <module>

    upper=int(30))

  File "/Users/georgeyoliver/GitHub/CSDS/GeoDaCenter/spatial_access/spatial_access/CommunityAnalytics.py", line 301, in __init__

    self.load_sp_matrix(sp_matrix_filename)

  File "/Users/georgeyoliver/miniconda3/envs/web_app/lib/python3.6/site-packages/spatial_access/ScoreModel.py", line 307, in load_sp_matrix

    self.dicto[row[0]][int(float(self.dest_2[i]))] = int(float(row[i]))     

ValueError: could not convert string to float:

**Comment by gyoliver** [comment]
@lmnoel I believe the issue might be in writeCSV method in the C++ code?  If it's a simple enough fix, do you think you could add it to master? It'll help me move forward with creating the web_app repo.

**Comment by lmnoel** [comment]
Give the new commit a try

**Comment by lmnoel** [comment]
Well... Looks like that commit broke something actually

**Comment by gyoliver** [comment]
No change here.  I could remove the column with pandas as a quick temp fix if the issue is more involved than expected.

**Comment by lmnoel** [comment]
yeah go for it, I'll PR it in once it passes Travis

**Comment by lmnoel** [comment]
Yeah, if you could, that would probably be fastest. Sorry bout that, haven't pushed to master in ages because v1.4 is becoming larger and larger

**Comment by gyoliver** [comment]
Ok, will do!
