### ISSUE TITLE
Investigate removing libspatialindex dependency

### ISSUE THREAD

**Issue by lmnoel** [GeoDaCenter/spatial_access#36]
geopandas spatial join requires installation of libspatialindex by brew/apt-get. Try to find an alternative implementation of spatial joins to simplify installation

**Comment by jkoschinsky** [comment]
from Xun: GeoDa uses boost::rtree and libgeos(via gdal/ogr) for parallel
spatial joins in case that's helpful

**Comment by lmnoel** [comment]
Unfortunately I don't think that would help--the problem is that my current solution requires installing a library with a system package manager (aka outside of python)--relatively much more complicated than pip installing. Boost and GDAL have the same problem, as far as I know--although please let me know if I'm wrong

**Comment by lixun910** [comment]
@lmnoel I see you are dynamic linking protobuf library, which is also required to be installed outside of python. Can you install libspatialindex with libprotobuf?

Another way is to implement spatial join from scrach if you only do points-n-polygon spatial joining: there are many headers only R-tree for spatial join, and you just need to add points-n-polygon detection code.

**Comment by lmnoel** [comment]
@lixun910 Actually in the process of removing protobuf right now, trying to eliminate the need for all non-standard libraries. 

I will definitely look in to implementing it from scratch if nothing better comes up
