### ISSUE TITLE
importing csv matrix into metrics

### ISSUE THREAD

**Issue by ifarah** [GeoDaCenter/spatial_access#43]
Now it's only reading H5.
Now user cannot compute metrics if she has a csv matrix.

**Comment by ifarah** [comment]
Issues with labels when reading in matrix in csv format.

access = AccessModel(network_type='walk',
                      sources_filename='ORIG/ct.csv',
                      source_column_names=None,
                      destinations_filename='DEST/marynia_health.csv',
                      dest_column_names=None,
                      transit_matrix_filename='matrices/ct_health.csv',
                    decay_function='logit')

access.calculate(upper_threshold=1800,category_weight_dict=dict, normalize=False)

<img width="865" alt="Screen Shot 2019-05-14 at 3 36 27 PM" src="https://user-images.githubusercontent.com/22567155/57730429-169e7e80-765e-11e9-9818-26789a0982d3.png">

**Comment by lmnoel** [comment]
@ifarah I'm unable to replicate the issue with a different dataset. Can you send ORIG/ct.csv

**Comment by lmnoel** [comment]
Solved, patch deploying now. The issue was that the indices of the destination dataset in the transit matrix csv were mistakenly treated as strings when they were actually integers. I was unable to replicate because I was using a dataset with string destination indices.
