### ISSUE TITLE
driving time impedence?

### ISSUE THREAD

**Issue by ifarah** [GeoDaCenter/spatial_access#45]
Comparing Dan's matrix, a difference of 10 minutes on average.

**Comment by jkoschinsky** [comment]
our driving times are 10 minutes lower than OTPs and were below the lowest time threshold in Google for the test cases we looked at (for non-rush-hour times): can we up our impedance?

**Comment by lmnoel** [comment]
Interesting observation: There are many segments in the driving network that are just a few meters long. Because I'm using integers for these values (as opposed to floats, which OTP uses I think), when divided by high speeds, these edges turn in to 0. I'm still trying different combinations of node impedance/edge rate to account for this best.

**Comment by ifarah** [comment]
@lmnoel , did you get it working yesterday or is the problem elsewhere?

**Comment by lmnoel** [comment]
Didn't have enough time yesterday. I'll be back in this afternoon.

**Comment by ifarah** [comment]
awesome, thanks! let me know if I can help with anything

**Comment by lmnoel** [comment]
Actually @ifarah, I think I have a slightly different version of the tracts dataset than your tracts2010.csv file. Could you send me that exact one?

**Comment by lmnoel** [comment]
Using the tracts Irene sampled, the original edge weight model of p2p gave the following (first value is mean(dan's time - p2p's time) in seconds, second value is std dev:

```
diff_17031836200
972.1290726817043
369.5565549537744
diff_17031071100
779.3771929824561
346.8469111225043
diff_17031561100
1137.9649122807018
348.7904301116148
```

When I step down each edge weight to 40% of its original value and add a 4s node penalty, we get the following:
```
diff_17031836200
149.15288220551378
91.72946796319982
diff_17031071100
5.053884711779449
113.99102235752898
diff_17031561100
33.177944862155385
127.18073532449111
```
original model
![original](https://user-images.githubusercontent.com/20692394/56437588-a6dae500-62a5-11e9-804b-8e5c9b9dcbc4.png)
original model diff
![original_diff](https://user-images.githubusercontent.com/20692394/56437589-a6dae500-62a5-11e9-8b91-3061caa7dd00.png)
modified model
![modified](https://user-images.githubusercontent.com/20692394/56437593-aa6e6c00-62a5-11e9-95be-dee61b6455c6.png)
modified model diff
![modified_diff](https://user-images.githubusercontent.com/20692394/56437595-aa6e6c00-62a5-11e9-9697-fc5036b7cbbf.png)


The correlation between dan's predicted time and error was crazy high in the original model (r>0.99). In the modified version it drops to r=0.58.

So the quality of the model seems to be entirely dependent on the quality of the actual driving speed data that is given as input.

**Comment by lmnoel** [comment]
I'll push up these changes in the next hour or so

**Comment by ifarah** [comment]
It totally makes sense that the quality of the model depends on quality of driving speed right? That would be in the config settings? or where are you tweaking that?

**Comment by lmnoel** [comment]
yeah

**Comment by ifarah** [comment]
Are you still working on this, @lmnoel ?

**Comment by lmnoel** [comment]
Not currently, and I have no plans to unless you need anything further
