### ISSUE TITLE
ERROR: Running driving times 

### ISSUE THREAD

**Issue by ifarah** [GeoDaCenter/spatial_access#62]
When running these files I got this error:

<img width="1462" alt="Screen Shot 2019-04-24 at 5 41 55 PM" src="https://user-images.githubusercontent.com/22567155/56698659-4d652280-66b8-11e9-9de2-3675c259d1e4.png">

<img width="1904" alt="Screen Shot 2019-04-24 at 5 41 48 PM" src="https://user-images.githubusercontent.com/22567155/56698666-535b0380-66b8-11e9-87ed-fffefb9bf7b1.png">

I created a new ID column instead of geoid10, but not sure what the problem is.

**Comment by lmnoel** [comment]
Your BLOCKS_ORIGINS dataset looks like:

GEOID10,COORD_X,COORD_Y
1.8148E+14,-86.9930031,37.98613057
2.1059E+14,-86.99349722,37.91392317
1.8148E+14,-86.99901778,37.99865051
2.1059E+14,-86.99945751,37.83672595
1.8148E+14,-87.00077926,37.92771384
2.1059E+14,-87.00141549,37.90682643
2.1059E+14,-87.00186158,37.87610695

somewhere along the line your id must have been converted from an int, so they are nonunique

**Comment by lmnoel** [comment]
(I will add a more descriptive error message so this is easier to debug in the future)

**Comment by ifarah** [comment]
I did generate a unique ID, though, and it still didn;t run
