### ISSUE TITLE
ERROR: Running driving meters (increase "infinity")

### ISSUE THREAD

**Issue by ifarah** [GeoDaCenter/spatial_access#63]
For estimating meters, this ran super fast but gave me **almost** all "infinity" since the distances are really large. Is there a way to increase "infinity"?

<img width="1221" alt="Screen Shot 2019-04-24 at 5 45 32 PM" src="https://user-images.githubusercontent.com/22567155/56698881-117e8d00-66b9-11e9-8744-d07cf70fbbca.png">

<img width="1134" alt="Screen Shot 2019-04-24 at 5 45 40 PM" src="https://user-images.githubusercontent.com/22567155/56698918-383cc380-66b9-11e9-9ff2-fc47ba3d5e74.png">

**Comment by ifarah** [comment]
Where can we expand the spatial extent? Now it's set approximately to 60 km? Or what is the maximum area for computing the actual value?

**Comment by ifarah** [comment]
Also, could 'infinity' be set as a different number than '65535'? Now it it seems like an actual value. Could it be '-1' instead?

**Comment by ifarah** [comment]
I want to change line 44 of NetworkInterface.py:
self.area_threshold = None if disable_area_threshold else **5000**  # km

I changed the line locally, but it's not reading it when I read in the package.
how can I change things

**Comment by lmnoel** [comment]
I'm not completely sure what you are asking. Will you be in at ~2?

**Comment by ifarah** [comment]
It's basically throwing an error because the bounding box is too large. The maximum is 2000 km2, but the bounding box for Chicago is 2067.3912994771686km2

**Comment by lmnoel** [comment]
The bounding box too large and the 65535 are two separate issues--the boolean flag in the TransitMatrix should disable the bounding box too large exception. Is that not the case?

**Comment by ifarah** [comment]
Yes. I agree they are two issues.
Not sure what flag you're talking about.
I'll be here at 2 pm.

**Comment by lmnoel** [comment]
clarified in #64
