### ISSUE TITLE
ERROR: tsfca 

### ISSUE THREAD

**Issue by ifarah** [GeoDaCenter/spatial_access#68]
I tried tsfca with different data and run every time into the same issue.
Do you know what's happening @lmnoel?:
<img width="952" alt="Screen Shot 2019-04-29 at 12 15 29 PM" src="https://user-images.githubusercontent.com/22567155/56913983-9500fb00-6a78-11e9-88ed-3b6fe8716075.png">

**Comment by lmnoel** [comment]
Does the same issue occur if you aren't loading the transit matrix from csv?

**Comment by ifarah** [comment]
It does work with tmx.

**Comment by ifarah** [comment]
When I don't specify a matrix, I can't specify "disable_area_threshold=True" and the area is too small for it to run (which would be a separate issue in itself.)

**Comment by lmnoel** [comment]
re: the disable_area_threshold issue, I am moving all transit matrix-related default argument to the Configs class which will be passed down from a Model to BaseModel to p2p

**Comment by lmnoel** [comment]
could you install the latest version and try again?

**Comment by ifarah** [comment]
I tried upgrading it, uninstalling/installing and I get this error:
Command "/usr/local/opt/python/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-7g15tksc/spatial-access/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-c40icfau/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-7g15tksc/spatial-access/

**Comment by ifarah** [comment]
I don't know if you updated this or if it's a problem with the installation @lmnoel?

**Comment by lmnoel** [comment]
Sorry, it's definitely a problem on my end! It's been a super busy week and I haven't gotten to it yet, I hope to in the next couple days

**Comment by lmnoel** [comment]
@ifarah fixed

**Comment by lmnoel** [comment]
Also, I implemented the extended range option for the transit matrix. See the require_extended_range boolean in Configs

**Comment by ifarah** [comment]
Would this be the equivalent to disable_area_threshold? Not sure what the difference is between require_extended_range  and  disable_area_threshold @lmnoel

**Comment by lmnoel** [comment]
No. disable_area_threshold removes a synthetic limit on the area that a request can cover. require_extended_range increases the maximum impedance of any pair of locations from 65,535 to 4,294,967,295. Does that make more sense?

**Comment by ifarah** [comment]
Yes, sounds good!

**Comment by ifarah** [comment]
Could you please increase the default value to **5000** in line 44 of NetworkInterface.py?
self.area_threshold = None if disable_area_threshold else **5000** 

I believe now it's too small
