### ISSUE TITLE
add pooled results to output for categories

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/spatial_access#69]
When you run the access score with categories, the output includes results for all categories pooled and each category separately.

When you run the 2-stage FCA, time to nearest facility and count (haven't tried access-sum/sum of nearby attributes), the results are only for separate, not pooled categories.

You can get to the pooled results by summing but to save users that extra step, and for consistency, let's also include the pooled results by default for all spatial metrics.

**Comment by lmnoel** [comment]
pr #73
