### ISSUE TITLE
Check for disconnected nodes in OD matrix

### ISSUE THREAD

**Issue by ifarah** [GeoDaCenter/spatial_access#7]

**Comment by jkoschinsky** [comment]
Meet with Shiv for overview of his related code updates

**Comment by lixun910** [comment]
@lmnoel  2cents:  For the disconnected nodes,  if OSM network removes node that only appears in one edge before analysis, then it might cause a problem to find nearest nodes that connect two subgraphs.

How about find the closest pair of nodes that connect two subgraphs, mark them (don't delete them). Then, let OSM network do the removing job?

**Comment by lmnoel** [comment]
Good idea. Will investigate.
