### ISSUE TITLE
Scalable solution

### ISSUE THREAD

**Issue by ifarah** [GeoDaCenter/spatial_access#8]
Generate a solution to run parcels to amenities for all the US.

**Comment by lmnoel** [comment]
Technically the p2p/matrix computations are already run in parallel

**Comment by ifarah** [comment]
Ok, then maybe estimating some sort of buffer beforehand that would be approximate to the shortest distance of 30 minutes and download the bounding box for that area. So doing the analysis by patches in order to have the whole US at the end? Would that make sense?
