### ISSUE TITLE
Create option for output in meters and in seconds

### ISSUE THREAD

**Issue by ifarah** [GeoDaCenter/spatial_access#9]
Check for conversions in C++ and Python (cost_model, nn_primary, nn_secondary)

**Comment by jkoschinsky** [comment]
@lmnoel: Researchers in the medical center are currently waiting for this -- is it possible to frontload this update so they can use it?

**Comment by ifarah** [comment]
Thanks! I just sent Rhys an email telling her to please hold until Logan gets the fix. :)


________________________________

**Comment by lmnoel** [comment]
I can try to update the contracts repo to do that tonight (but I cannot attest to the stability of that build--haven't touched it since June) but would take ~ 2 weeks to get to in this repo because I've had to break everything in order to fix everything. 

Which should I prioritize?

**Comment by lmnoel** [comment]
Added in version 0.1.0
